version: "3"
services:
  db:
    build:
     context: ./db
     dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres_volume:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./app:/app

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_volume:
